name: CI/CD Homolog

on:
  push:
    branches: [main]

jobs:
  validate:
    uses: ./.github/workflows/ci-base.yml

  deploy-hml:
    needs: validate

    uses: ./.github/workflows/cd-base.yml
    with:
      deploy_env: hml
    secrets:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_HML }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF_HML }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD_HML }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
